### ISSUE TITLE
[addon] vendor.js:14614 Uncaught Error: Could not find module ember-routing-htmlbars/keywords/closure-action

### ISSUE THREAD

**Issue by GavinJoyce** [GavinJoyce/glammer#2]
**UPDATE:** this seems to be coming from https://github.com/DockYard/ember-route-action-helper 0.3.3. 

TODO:
- [x] recreate in this repo: https://github.com/GavinJoyce/glammer/tree/master/app/templates
- [x] open an issue : https://github.com/DockYard/ember-route-action-helper/issues/29

<img width="618" alt="screen shot 2016-07-29 at 15 17 18" src="https://cloud.githubusercontent.com/assets/2526/17251199/9b8b723e-559f-11e6-9988-5056ce1e4107.png">

**Comment by crhayes** [comment]
I experienced this as well. I upgraded to ember-route-action-helper `1.0.0` and confirmed the problem is fixed.
